version: '3'

services:
  app:
    build: .
    image: app
    container_name: app
    environment:
      JWT_SECRET: ${JWT_SECRET}

      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      STORAGE_DRIVER: s3

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}

    depends_on:
      - postgres
    networks:
      - app
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      - app
    volumes:
      - app:/var/lib/postgresql/data

volumes:
  app:

networks:
  app:
    driver: bridge